version: '3.8'
services:
  telemetry_test2:
    image: telemetry_test2
    container_name: telemetry_test2
    depends_on:
      - otel-collector
    networks:
      - opentelemetry-test

  kafka_consumer_app:
    image: kafka_consumer_test 
    container_name: kafka_consumer_test
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092 
      SPRING_KAFKA_CONSUMER_GROUP-ID: otel
      SPRING_KAFKA_CONSUMER_AUTO-OFFSET-RESET: earliest
    depends_on:
      - kafka
    networks:
      - opentelemetry-test

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"  # OTLP gRPC 포트
      - "4318:4318"  # OTLP HTTP 포트
    networks:
      - opentelemetry-test

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "otel-traces:1:1"
    ports:
      - "9092:9092"
    networks:
      - opentelemetry-test

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - opentelemetry-test

networks:
  opentelemetry-test:
    driver: bridge
