version: "3.8"
services:
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "otel-traces:1:1"
    ports:
      - "9092:9092"
    networks:
      - opentelemetry-test

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - opentelemetry-test

networks:
  opentelemetry-test:
    external: true
