exporters:
  kafka:
    brokers:
      - "kafka:9092"  # Kafka 서비스 이름과 포트
    topic: otel-traces  # 데이터를 보낼 Kafka 토픽

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [kafka]
