spring:
  application:
    name: kafka_consumer_test
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: otel
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
